version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8050:8080
    command: start-dev --import-realm
    volumes:
        - ./config/propet.json:/opt/keycloak/data/import/propet.json:ro
  backend:
    image: deividrx/propet-service
    depends_on:
      - db
      - keycloak
    environment:
      POSTGRES_IP: db
      POSTGRES_PASSWD: admin
      KEYCLOAK_IP: keycloak
    ports:
      - 8088:8088
