server:
  port: 8088
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_IP_ANDRESS}:${DATABASE_PORT}/propet?characterEncoding=utf8?useTimezone=true?serverTimezone=UTC
    password: ${DATABASE_PASSWD}
    username: ${DATABASE_USER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
