name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: set up java 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17
        distribution: temurin
        cache: maven
        
    - name: build with maven
      run: ./mvnw clean package

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/propet-service:latest
      
    - name: Login Docker
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWD }}
    
    - name: Push to Dockerhub
      run: docker push ${{ secrets.DOCKER_USER }}/propet-service:latest
